name: Dispatch Command

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  dispatch-command:
    if: startsWith(github.repository, 'Homebrew/')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch /rebase Command
        uses: peter-evans/slash-command-dispatch@e1b4e266bc781656359bb7e462e228daf68c04f6
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
          reaction-token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
          commands: rebase
          permission: triage
          issue-type: pull-request
